[GLOBAL]
pythonpath = ["%(buildroot)s/pants-pytooling"]
pants_version = "2.9.0"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.docformatter",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.typecheck.mypy",
    "pytooling_distribution",
    "pytooling_readme"]
#   "pytooling_readme.package"]
pants_ignore = ["not"]
build_file_prelude_globs = [
  "pants-pytooling/macros.py",
]
plugins = ["jinja2"]

[python]
interpreter_constraints = [">=3.8.*"]

[test]
use_coverage = true

[pytest]
extra_requirements = [
    "pytest-cov>=2.10.1,<2.12",
    "pytest-patches"]
lockfile = ".pytest.lock"

[coverage-py]
report = ["console", "html"]

[anonymous-telemetry]
enabled = false

[source]
marker_filenames = ["setup.cfg"]
root_patterns = ["pants-pytooling"]

[mypy]
config = "mypy.ini"
extra_requirements = [
     "mypy-abstracts"]
extra_type_stubs = [
     "types-aiofiles",
     "types-frozendict",
     "types-psutil",
     "types-pytz",
     "types-pyyaml"]
args = [
     "--explicit-package-bases",
     "--namespace-packages",
     "--no-warn-no-return"]
lockfile = ".mypy.lock"
version = "mypy>=0.931"

[update-build-files]
fmt = false
