[GLOBAL]
pythonpath = ["%(buildroot)s/pants-pytooling"]
pants_version = "2.6.1"
backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.docformatter",
    "pants.backend.python.lint.flake8",
    "pants.backend.python.typecheck.mypy",
    "pytooling_distribution",
    "pytooling_readme"]

#            "pytooling_readme.package"]
pants_ignore = ["not"]
build_file_prelude_globs = [
  "pants-pytooling/macros.py",
]
plugins = ["jinja2"]

[python-setup]
interpreter_constraints = [">=3.8.*"]

[test]
use_coverage = true

[pytest]
pytest_plugins = [
    "pytest-cov>=2.10.1,<2.12",
    "pytest-patches",
]

[coverage-py]
report = ["console", "html"]

[anonymous-telemetry]
enabled = false

[source]
marker_filenames = ["setup.cfg"]
root_patterns = ["pants-pytooling"]

[mypy]
config = "mypy.ini"
extra_requirements = [
     "mypy-abstracts",
     "types-aiofiles",
     "types-frozendict",
     "types-protobuf",
     "types-pyyaml"]
args = [
     "--explicit-package-bases",
     "--namespace-packages",
     "--no-warn-no-return"]
