name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - name: Install pants
      run: pip install pantsbuild.pants
    - name: Run pants test
      run: "pants test ::"
    - name: Archive code coverage results
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: dist/coverage/python/htmlcov/

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - name: Install pants
      run: pip install pantsbuild.pants
    - name: Run pants lint
      run: "pants lint ::"

  package:
    runs-on: ubuntu-latest
    needs:
    - test
    - lint
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
    - name: Install pants
      run: pip install pantsbuild.pants
    - name: Run pants package
      run: "pants package ::"
